# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/JamesWilliamson/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_0_100M_1/MicroBlaze_rst_clk_wiz_0_100M_1.xci
# IP: The module: 'MicroBlaze_rst_clk_wiz_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JamesWilliamson/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_0_100M_1/MicroBlaze_rst_clk_wiz_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_rst_clk_wiz_0_100M_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/JamesWilliamson/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_0_100M_1/MicroBlaze_rst_clk_wiz_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_rst_clk_wiz_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/JamesWilliamson/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_0_100M_1/MicroBlaze_rst_clk_wiz_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_rst_clk_wiz_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/JamesWilliamson/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_0_100M_1/MicroBlaze_rst_clk_wiz_0_100M_1.xci
# IP: The module: 'MicroBlaze_rst_clk_wiz_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JamesWilliamson/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_0_100M_1/MicroBlaze_rst_clk_wiz_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_rst_clk_wiz_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/JamesWilliamson/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_0_100M_1/MicroBlaze_rst_clk_wiz_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_rst_clk_wiz_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/JamesWilliamson/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_0_100M_1/MicroBlaze_rst_clk_wiz_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_rst_clk_wiz_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
