# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_xbar_1/MicroBlaze_xbar_1.xci
# IP: The module: 'MicroBlaze_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_xbar_1/MicroBlaze_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_xbar_1/MicroBlaze_xbar_1.xci
# IP: The module: 'MicroBlaze_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_xbar_1/MicroBlaze_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
