# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_HardwareXCorr_wrapper_0_0/MicroBlaze_HardwareXCorr_wrapper_0_0.xci
# IP: The module: 'MicroBlaze_HardwareXCorr_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/HardwareXCorr.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr || ORIG_REF_NAME==HardwareXCorr} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_CC_0_0/HardwareXCorr_CC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_CC_0_0 || ORIG_REF_NAME==HardwareXCorr_CC_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_clk100khz_0_0/HardwareXCorr_clk100khz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_clk100khz_0_0 || ORIG_REF_NAME==HardwareXCorr_clk100khz_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_clk_wiz_0_0/HardwareXCorr_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_clk_wiz_0_0 || ORIG_REF_NAME==HardwareXCorr_clk_wiz_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_waveParser_0_0/HardwareXCorr_waveParser_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_waveParser_0_0 || ORIG_REF_NAME==HardwareXCorr_waveParser_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_dds_compiler_1_0/HardwareXCorr_dds_compiler_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_dds_compiler_1_0 || ORIG_REF_NAME==HardwareXCorr_dds_compiler_1_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_xlslice_0_0/HardwareXCorr_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_xlslice_0_0 || ORIG_REF_NAME==HardwareXCorr_xlslice_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_0_0/HardwareXCorr_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_0_0 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_0_1/HardwareXCorr_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_0_1 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_0_1} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_0_2/HardwareXCorr_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_0_2 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_0_2} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_0_3/HardwareXCorr_blk_mem_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_0_3 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_0_3} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_xlconstant_0_0/HardwareXCorr_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_xlconstant_0_0 || ORIG_REF_NAME==HardwareXCorr_xlconstant_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_4_0/HardwareXCorr_blk_mem_gen_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_4_0 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_4_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_4_1/HardwareXCorr_blk_mem_gen_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_4_1 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_4_1} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_4_2/HardwareXCorr_blk_mem_gen_4_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_4_2 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_4_2} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_4_3/HardwareXCorr_blk_mem_gen_4_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_4_3 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_4_3} -quiet] -quiet

# IP: c:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_AddressFixer_0_0/HardwareXCorr_AddressFixer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_AddressFixer_0_0 || ORIG_REF_NAME==HardwareXCorr_AddressFixer_0_0} -quiet] -quiet

# XDC: c:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/HardwareXCorr/HardwareXCorr_ooc.xdc

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_HardwareXCorr_wrapper_0_0/MicroBlaze_HardwareXCorr_wrapper_0_0.xci
# IP: The module: 'MicroBlaze_HardwareXCorr_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/HardwareXCorr.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr || ORIG_REF_NAME==HardwareXCorr} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_CC_0_0/HardwareXCorr_CC_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_CC_0_0 || ORIG_REF_NAME==HardwareXCorr_CC_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_clk100khz_0_0/HardwareXCorr_clk100khz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_clk100khz_0_0 || ORIG_REF_NAME==HardwareXCorr_clk100khz_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_clk_wiz_0_0/HardwareXCorr_clk_wiz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_clk_wiz_0_0 || ORIG_REF_NAME==HardwareXCorr_clk_wiz_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_waveParser_0_0/HardwareXCorr_waveParser_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_waveParser_0_0 || ORIG_REF_NAME==HardwareXCorr_waveParser_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_dds_compiler_1_0/HardwareXCorr_dds_compiler_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_dds_compiler_1_0 || ORIG_REF_NAME==HardwareXCorr_dds_compiler_1_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_xlslice_0_0/HardwareXCorr_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_xlslice_0_0 || ORIG_REF_NAME==HardwareXCorr_xlslice_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_0_0/HardwareXCorr_blk_mem_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_0_0 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_0_1/HardwareXCorr_blk_mem_gen_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_0_1 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_0_1} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_0_2/HardwareXCorr_blk_mem_gen_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_0_2 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_0_2} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_0_3/HardwareXCorr_blk_mem_gen_0_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_0_3 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_0_3} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_xlconstant_0_0/HardwareXCorr_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_xlconstant_0_0 || ORIG_REF_NAME==HardwareXCorr_xlconstant_0_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_4_0/HardwareXCorr_blk_mem_gen_4_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_4_0 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_4_0} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_4_1/HardwareXCorr_blk_mem_gen_4_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_4_1 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_4_1} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_4_2/HardwareXCorr_blk_mem_gen_4_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_4_2 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_4_2} -quiet] -quiet

# IP: C:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_blk_mem_gen_4_3/HardwareXCorr_blk_mem_gen_4_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_blk_mem_gen_4_3 || ORIG_REF_NAME==HardwareXCorr_blk_mem_gen_4_3} -quiet] -quiet

# IP: c:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/HardwareXCorr/ip/HardwareXCorr_AddressFixer_0_0/HardwareXCorr_AddressFixer_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareXCorr_AddressFixer_0_0 || ORIG_REF_NAME==HardwareXCorr_AddressFixer_0_0} -quiet] -quiet

# XDC: c:/Users/JamesWilliamson/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/HardwareXCorr/HardwareXCorr_ooc.xdc
