# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_xbar_0/MicroBlaze_xbar_0.xci
# IP: The module: 'MicroBlaze_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_xbar_0/MicroBlaze_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_xbar_0/MicroBlaze_xbar_0.xci
# IP: The module: 'MicroBlaze_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_xbar_0/MicroBlaze_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
