# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/JamesWilliamson/Downloads/Cmod-S7-25-Master.xdc

# Block Designs: bd/HydroDSP/HydroDSP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP || ORIG_REF_NAME==HydroDSP} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_dds_compiler_0_0/HydroDSP_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_dds_compiler_0_0 || ORIG_REF_NAME==HydroDSP_dds_compiler_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_dds_compiler_1_0/HydroDSP_dds_compiler_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_dds_compiler_1_0 || ORIG_REF_NAME==HydroDSP_dds_compiler_1_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_clk_wiz_0_0/HydroDSP_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_clk_wiz_0_0 || ORIG_REF_NAME==HydroDSP_clk_wiz_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_clk100khz_0_0/HydroDSP_clk100khz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_clk100khz_0_0 || ORIG_REF_NAME==HydroDSP_clk100khz_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_0_0/HydroDSP_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_0_0 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_0_1/HydroDSP_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_0_1 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_0_2/HydroDSP_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_0_2 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_0_3/HydroDSP_blk_mem_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_0_3 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_0_3} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_0_4/HydroDSP_blk_mem_gen_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_0_4 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_0_4} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_1_0/HydroDSP_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_1_0 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_2_0/HydroDSP_blk_mem_gen_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_2_0 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_2_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_3_0/HydroDSP_blk_mem_gen_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_3_0 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_3_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_xlconstant_0_0/HydroDSP_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_xlconstant_0_0 || ORIG_REF_NAME==HydroDSP_xlconstant_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_waveParser_0_0/HydroDSP_waveParser_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_waveParser_0_0 || ORIG_REF_NAME==HydroDSP_waveParser_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_clk_wiz_1_0/HydroDSP_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_clk_wiz_1_0 || ORIG_REF_NAME==HydroDSP_clk_wiz_1_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_CC_0_0/HydroDSP_CC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_CC_0_0 || ORIG_REF_NAME==HydroDSP_CC_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_DataCompressor_0_0/HydroDSP_DataCompressor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_DataCompressor_0_0 || ORIG_REF_NAME==HydroDSP_DataCompressor_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_8_0/HydroDSP_blk_mem_gen_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_8_0 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_8_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_axi_uartlite_0_0/HydroDSP_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_axi_uartlite_0_0 || ORIG_REF_NAME==HydroDSP_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_mdm_1_0/HydroDSP_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_mdm_1_0 || ORIG_REF_NAME==HydroDSP_mdm_1_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_rst_clk_wiz_0_200M_0/HydroDSP_rst_clk_wiz_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_rst_clk_wiz_0_200M_0 || ORIG_REF_NAME==HydroDSP_rst_clk_wiz_0_200M_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_axi_bram_ctrl_0_0/HydroDSP_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_axi_bram_ctrl_0_0 || ORIG_REF_NAME==HydroDSP_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_xlconstant_1_0/HydroDSP_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_xlconstant_1_0 || ORIG_REF_NAME==HydroDSP_xlconstant_1_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_clk_wiz_2_0/HydroDSP_clk_wiz_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_clk_wiz_2_0 || ORIG_REF_NAME==HydroDSP_clk_wiz_2_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_microblaze_0_5/HydroDSP_microblaze_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_microblaze_0_5 || ORIG_REF_NAME==HydroDSP_microblaze_0_5} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_dlmb_v10_5/HydroDSP_dlmb_v10_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_dlmb_v10_5 || ORIG_REF_NAME==HydroDSP_dlmb_v10_5} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_ilmb_v10_5/HydroDSP_ilmb_v10_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_ilmb_v10_5 || ORIG_REF_NAME==HydroDSP_ilmb_v10_5} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_dlmb_bram_if_cntlr_5/HydroDSP_dlmb_bram_if_cntlr_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_dlmb_bram_if_cntlr_5 || ORIG_REF_NAME==HydroDSP_dlmb_bram_if_cntlr_5} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_ilmb_bram_if_cntlr_5/HydroDSP_ilmb_bram_if_cntlr_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_ilmb_bram_if_cntlr_5 || ORIG_REF_NAME==HydroDSP_ilmb_bram_if_cntlr_5} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_lmb_bram_5/HydroDSP_lmb_bram_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_lmb_bram_5 || ORIG_REF_NAME==HydroDSP_lmb_bram_5} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_xbar_1/HydroDSP_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_xbar_1 || ORIG_REF_NAME==HydroDSP_xbar_1} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_microblaze_0_axi_periph_1/HydroDSP_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_microblaze_0_axi_periph_1 || ORIG_REF_NAME==HydroDSP_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_microblaze_0_axi_intc_1/HydroDSP_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_microblaze_0_axi_intc_1 || ORIG_REF_NAME==HydroDSP_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_microblaze_0_xlconcat_1/HydroDSP_microblaze_0_xlconcat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_microblaze_0_xlconcat_1 || ORIG_REF_NAME==HydroDSP_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_auto_pc_0/HydroDSP_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_auto_pc_0 || ORIG_REF_NAME==HydroDSP_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/JamesWilliamson/Cascade_hydrophones/Hardware/XCORR/XCORR.gen/sources_1/bd/HydroDSP/HydroDSP_ooc.xdc
