# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/HydroDSP/HydroDSP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP || ORIG_REF_NAME==HydroDSP} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_dds_compiler_0_0/HydroDSP_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_dds_compiler_0_0 || ORIG_REF_NAME==HydroDSP_dds_compiler_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_dds_compiler_1_0/HydroDSP_dds_compiler_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_dds_compiler_1_0 || ORIG_REF_NAME==HydroDSP_dds_compiler_1_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_clk_wiz_0_0/HydroDSP_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_clk_wiz_0_0 || ORIG_REF_NAME==HydroDSP_clk_wiz_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_clk100khz_0_0/HydroDSP_clk100khz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_clk100khz_0_0 || ORIG_REF_NAME==HydroDSP_clk100khz_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_0_0/HydroDSP_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_0_0 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_0_1/HydroDSP_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_0_1 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_0_2/HydroDSP_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_0_2 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_0_3/HydroDSP_blk_mem_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_0_3 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_0_3} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_0_4/HydroDSP_blk_mem_gen_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_0_4 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_0_4} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_1_0/HydroDSP_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_1_0 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_2_0/HydroDSP_blk_mem_gen_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_2_0 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_2_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_blk_mem_gen_3_0/HydroDSP_blk_mem_gen_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_blk_mem_gen_3_0 || ORIG_REF_NAME==HydroDSP_blk_mem_gen_3_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_xlconstant_0_0/HydroDSP_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_xlconstant_0_0 || ORIG_REF_NAME==HydroDSP_xlconstant_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_waveParser_0_0/HydroDSP_waveParser_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_waveParser_0_0 || ORIG_REF_NAME==HydroDSP_waveParser_0_0} -quiet] -quiet

# IP: bd/HydroDSP/ip/HydroDSP_CC_0_0/HydroDSP_CC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HydroDSP_CC_0_0 || ORIG_REF_NAME==HydroDSP_CC_0_0} -quiet] -quiet

# XDC: c:/Users/JamesWilliamson/Xcorr/xCorr.gen/sources_1/bd/HydroDSP/HydroDSP_ooc.xdc
