# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/james/Downloads/ebaz4205.xdc

# Block Designs: bd/MicroBlaze/MicroBlaze.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze || ORIG_REF_NAME==MicroBlaze} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_axi_gpio_0_0/MicroBlaze_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_axi_gpio_0_0 || ORIG_REF_NAME==MicroBlaze_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_axi_gpio_0_1/MicroBlaze_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_axi_gpio_0_1 || ORIG_REF_NAME==MicroBlaze_axi_gpio_0_1} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_SineWaveGen_0_0/MicroBlaze_SineWaveGen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_SineWaveGen_0_0 || ORIG_REF_NAME==MicroBlaze_SineWaveGen_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_clk_wiz_0_0/MicroBlaze_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_clk_wiz_0_0 || ORIG_REF_NAME==MicroBlaze_clk_wiz_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_SPI_ADC_Master_0_1/MicroBlaze_SPI_ADC_Master_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_SPI_ADC_Master_0_1 || ORIG_REF_NAME==MicroBlaze_SPI_ADC_Master_0_1} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_Serializer_0_0/MicroBlaze_Serializer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_Serializer_0_0 || ORIG_REF_NAME==MicroBlaze_Serializer_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_SPI_ADC_Master_1_0/MicroBlaze_SPI_ADC_Master_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_SPI_ADC_Master_1_0 || ORIG_REF_NAME==MicroBlaze_SPI_ADC_Master_1_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_Serializer_1_0/MicroBlaze_Serializer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_Serializer_1_0 || ORIG_REF_NAME==MicroBlaze_Serializer_1_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_SPI_ADC_Master_2_0/MicroBlaze_SPI_ADC_Master_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_SPI_ADC_Master_2_0 || ORIG_REF_NAME==MicroBlaze_SPI_ADC_Master_2_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_Serializer_2_0/MicroBlaze_Serializer_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_Serializer_2_0 || ORIG_REF_NAME==MicroBlaze_Serializer_2_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_clk1Mhz_0_1/MicroBlaze_clk1Mhz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_clk1Mhz_0_1 || ORIG_REF_NAME==MicroBlaze_clk1Mhz_0_1} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_MaximumFinder_0_0/MicroBlaze_MaximumFinder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_MaximumFinder_0_0 || ORIG_REF_NAME==MicroBlaze_MaximumFinder_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_SineWaveGen_0_1/MicroBlaze_SineWaveGen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_SineWaveGen_0_1 || ORIG_REF_NAME==MicroBlaze_SineWaveGen_0_1} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_xlslice_0_0/MicroBlaze_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_xlslice_0_0 || ORIG_REF_NAME==MicroBlaze_xlslice_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_xlslice_0_1/MicroBlaze_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_xlslice_0_1 || ORIG_REF_NAME==MicroBlaze_xlslice_0_1} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_Wrapper_XCorr_0_0/MicroBlaze_Wrapper_XCorr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_Wrapper_XCorr_0_0 || ORIG_REF_NAME==MicroBlaze_Wrapper_XCorr_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_SineWaveGen_2_0/MicroBlaze_SineWaveGen_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_SineWaveGen_2_0 || ORIG_REF_NAME==MicroBlaze_SineWaveGen_2_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_axi_gpio_2_0/MicroBlaze_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_axi_gpio_2_0 || ORIG_REF_NAME==MicroBlaze_axi_gpio_2_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_WaveCaptureUnit_0_0/MicroBlaze_WaveCaptureUnit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_WaveCaptureUnit_0_0 || ORIG_REF_NAME==MicroBlaze_WaveCaptureUnit_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_axi_gpio_3_0/MicroBlaze_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_axi_gpio_3_0 || ORIG_REF_NAME==MicroBlaze_axi_gpio_3_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_processing_system7_0_1/MicroBlaze_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_processing_system7_0_1 || ORIG_REF_NAME==MicroBlaze_processing_system7_0_1} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_axi_smc_1/MicroBlaze_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_axi_smc_1 || ORIG_REF_NAME==MicroBlaze_axi_smc_1} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_rst_ps7_0_200M_0/MicroBlaze_rst_ps7_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_rst_ps7_0_200M_0 || ORIG_REF_NAME==MicroBlaze_rst_ps7_0_200M_0} -quiet] -quiet

# XDC: c:/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/MicroBlaze_ooc.xdc
