# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/JamesWilliamson/Documents/GitHub/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_lmb_bram_2/MicroBlaze_lmb_bram_2.xci
# IP: The module: 'MicroBlaze_lmb_bram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JamesWilliamson/Documents/GitHub/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_lmb_bram_2/MicroBlaze_lmb_bram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_lmb_bram_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/JamesWilliamson/Documents/GitHub/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_lmb_bram_2/MicroBlaze_lmb_bram_2.xci
# IP: The module: 'MicroBlaze_lmb_bram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JamesWilliamson/Documents/GitHub/Cascade_hydrophones/WorkspaceOMDHydrophones/Hardware/HydroProccess/HydroProccess.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_lmb_bram_2/MicroBlaze_lmb_bram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_lmb_bram_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
