# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/JamesWilliamson/Xcorr/xCorr.srcs/sources_1/bd/HydroDSP/ip/HydroDSP_blk_mem_gen_1_0/HydroDSP_blk_mem_gen_1_0.xci
# IP: The module: 'HydroDSP_blk_mem_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JamesWilliamson/Xcorr/xCorr.gen/sources_1/bd/HydroDSP/ip/HydroDSP_blk_mem_gen_1_0/HydroDSP_blk_mem_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HydroDSP_blk_mem_gen_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/JamesWilliamson/Xcorr/xCorr.srcs/sources_1/bd/HydroDSP/ip/HydroDSP_blk_mem_gen_1_0/HydroDSP_blk_mem_gen_1_0.xci
# IP: The module: 'HydroDSP_blk_mem_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JamesWilliamson/Xcorr/xCorr.gen/sources_1/bd/HydroDSP/ip/HydroDSP_blk_mem_gen_1_0/HydroDSP_blk_mem_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HydroDSP_blk_mem_gen_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
